# -------------------------------------------------------
# Input variables
# Populated from terraform.tfvars.json generated by the CLI
# -------------------------------------------------------

variable "github_owner" {
  description = "GitHub organisation or user account that owns the resources"
  type        = string
}

variable "groups" {
  description = "Map of group name to list of usernames"
  type        = map(list(string))
}

variable "repositories" {
  description = "Map of app/repo key to repository configuration"
  type = map(object({
    app_name    = string
    name        = string
    visibility  = string
    description = string
  }))
}

variable "user_collaborators" {
  description = "Map of app/repo/user key to collaborator configuration"
  type = map(object({
    repo_key   = string
    user       = string
    permission = string
  }))
}

variable "team_permissions" {
  description = "Map of app/repo/group key to team permission configuration"
  type = map(object({
    repo_key   = string
    team       = string
    permission = string
  }))
}

variable "rulesets" {
  description = "Map of app/repo/ruleset key to ruleset configuration"
  type = map(object({
    name          = string
    repo_key      = string
    target_branch = string
    rules = object({
      pull_request = optional(object({
        required_approving_review_count  = optional(number, 0)
        required_conversation_resolution = optional(bool, false)
        required_review_from_code_owners = optional(bool, false)
      }))
      automatic_copilot_review = optional(object({
        review_new_push            = optional(bool, false)
        review_draft_pull_request  = optional(bool, false)
      }))
    })
  }))
}
