# -------------------------------------------------------
# Input variables
# Populated from terraform.tfvars.json generated by the CLI
# -------------------------------------------------------

variable "github_owner" {
  description = "GitHub organisation or user account that owns the resources"
  type        = string
}


